# Generated by Django 4.2.5 on 2023-09-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listsm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=255)),
                ('animal_description', models.TextField()),
                ('animal_shortname', models.SlugField(max_length=255, unique=True)),
                ('animal_published_date_time', models.DateTimeField(auto_now_add=True)),
                ('animal_image', models.ImageField(blank=True, upload_to='mylist/images')),
            ],
        ),
    ]
